name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Triggers when code is pushed to the main branch

jobs:
  docker_build:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log into Docker Hub using GitHub Secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.RAJU_DOCKER_USERNAME }}
          password: ${{ secrets.RAJU_DOCKER_PASSWORD }}

      # Step 4: Build Docker image and tag it correctly
      - name: Build Docker Image
        run: |
          docker buildx build --push --tag rajudevop/azure-project:latest --file Dockerfile .

      # Step 5: Push the Docker image to Docker Hub
      - name: Push Docker Image to Docker Hub
        run: |
          docker push rajudevop/azure-project:latest
