name: Build and Push Docker Image to Docker Hub

# Trigger the workflow when changes are pushed to the main branch.
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (for building the image)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub using the stored secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.RAJU_DOCKER_USERNAME }}
          password: ${{ secrets.RAJU_DOCKER_PASSWORD }}

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          docker buildx build --raju15004/rajudevop/azure-project:latest .

      # Step 5: Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker buildx build --push --raju15004/rajudevop/azure-project:latest .
