name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Runs when pushing to the main branch.

jobs:
  lint_dockerfile:
    runs-on: ubuntu-latest
    name: STAGE1: LINTING DOCKERFILES
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install hadolint (Dockerfile linter)
        run: |
          sudo apt-get update && sudo apt-get install -y hadolint

      - name: Lint Dockerfile
        run: |
          hadolint Dockerfile  # Lint the Dockerfile

  docker_build:
    runs-on: ubuntu-latest
    name: STAGE2: BUILD AND PUSH DOCKER IMAGE
    needs: lint_dockerfile  # Ensure STAGE2 runs after STAGE1 is successful
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.RAJU_DOCKER_USERNAME }}
          password: ${{ secrets.RAJU_DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker buildx build --platform linux/amd64 --push \
          -t raju15004/raju-azure-app:latest -f Dockerfile .
