name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  lint_and_checkov:
    runs-on: ubuntu-latest
    name: STAGE1: LINTING AND CHECKOV
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and Run Linter (flake8)
        run: |
          pip install flake8 && flake8 .

      - name: Install and Run Checkov
        run: |
          pip install checkov && checkov -d .

  docker_build:
    runs-on: ubuntu-latest
    name: STAGE2: BUILD AND PUSH DOCKER IMAGE
    needs: lint_and_checkov  # Run this after linting and checkov
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.RAJU_DOCKER_USERNAME }}
          password: ${{ secrets.RAJU_DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker buildx build --platform linux/amd64 --push \
          -t raju15004/raju-azure-app:latest -f Dockerfile .
