name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Runs when pushing to the main branch.

jobs:
  linting:
    runs-on: ubuntu-latest
    name: STAGE1: LINTING
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version

      - name: Install Linter (flake8)
        run: |
          pip install flake8

      - name: Run Linter (flake8)
        run: |
          flake8 .  # Lint the repository

  docker_build:
    runs-on: ubuntu-latest
    name: STAGE2: BUILD AND PUSH DOCKER IMAGE
    needs: linting  # Ensures STAGE2 runs after STAGE1 is successful
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.RAJU_DOCKER_USERNAME }}
          password: ${{ secrets.RAJU_DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker buildx build --platform linux/amd64 --push \
          -t raju15004/raju-azure-app:latest -f Dockerfile .
