name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Runs when pushing to the main branch..

jobs:
  docker_build:
    runs-on: ubuntu-latest
    name: STAGE 1: BUILDING DOCKER IMAGE
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker buildx build --platform linux/amd64 \
          -t raju15004/raju-azure-app:latest -f Dockerfile .  # Build the image

      - name: Save Docker Image as a Cache
        run: |
          docker save raju15004/raju-azure-app:latest -o image.tar  # Save image to a tar file

  docker_push:
    runs-on: ubuntu-latest
    name: STAGE 2: PUSHING DOCKER IMAGE
    needs: docker_build  # Ensure STAGE 2 runs after STAGE 1 is successful

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.RAJU_DOCKER_USERNAME }}
          password: ${{ secrets.RAJU_DOCKER_PASSWORD }}

      - name: Load Docker Image from Cache
        run: |
          docker load -i image.tar  # Load the Docker image from the tar file

      - name: Push Docker Image to Docker Hub
        run: |
          docker push raju15004/raju-azure-app:latest  # Push the Docker image to Docker Hub
